version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_container'
    environment:
      - MONGO_INITDB_DATABASE=SmartHouseDatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db